CREATE TABLE IF NOT EXISTS "USERS" (
  "USER_ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "EMAIL" VARCHAR(255) NOT NULL,
  "LOGIN" VARCHAR(255) UNIQUE NOT NULL,
  "NAME" VARCHAR(255),
  "BIRTHDAY" DATE,
  CONSTRAINT USERS_PK PRIMARY KEY ("USER_ID")
);

CREATE TABLE IF NOT EXISTS "FRIENDS" (
  "USER_ID" BIGINT NOT NULL,
  "FRIEND_ID" BIGINT NOT NULL,
  "LAST_UDPATE" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FRIENDS_PK PRIMARY KEY ("USER_ID", "FRIEND_ID")
);

CREATE TABLE IF NOT EXISTS "FILMS" (
  "FILM_ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(255) NOT NULL,
  "DESCRIPTION" VARCHAR(200),
  "RELEASE_DATE" DATE NOT NULL,
  "DURATION" INTEGER NOT NULL,
  "MPA" BIGINT,
  CONSTRAINT FILM_PK PRIMARY KEY ("FILM_ID")
);

CREATE TABLE IF NOT EXISTS "GENRES" (
  "GENRE_ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(255) NOT NULL,
  CONSTRAINT GENRES_PK PRIMARY KEY ("GENRE_ID")
);

CREATE TABLE IF NOT EXISTS "FILM_GENRES" (
  "FILM_ID" BIGINT NOT NULL,
  "GENRE_ID" BIGINT NOT NULL,
  CONSTRAINT FILM_GENRES_PK PRIMARY KEY ("FILM_ID", "GENRE_ID")
);

CREATE TABLE IF NOT EXISTS "RATINGS" (
  "RATING_ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(255) NOT NULL,
  CONSTRAINT RATINGS_PK PRIMARY KEY ("RATING_ID")
);

CREATE TABLE IF NOT EXISTS "FILM_LIKES" (
  "FILM_ID" BIGINT NOT NULL,
  "USER_ID" BIGINT NOT NULL,
  CONSTRAINT FILM_LIKES_PK PRIMARY KEY ("FILM_ID", "USER_ID")
);

ALTER TABLE "FILM_LIKES" ADD FOREIGN KEY ("FILM_ID") REFERENCES "FILMS" ("FILM_ID");

ALTER TABLE "FILM_LIKES" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "FILMS" ADD FOREIGN KEY ("MPA") REFERENCES "RATINGS" ("RATING_ID");

ALTER TABLE "FILM_GENRES" ADD FOREIGN KEY ("FILM_ID") REFERENCES "FILMS" ("FILM_ID");

ALTER TABLE "FILM_GENRES" ADD FOREIGN KEY ("GENRE_ID") REFERENCES "GENRES" ("GENRE_ID");

ALTER TABLE "FRIENDS" ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "FRIENDS" ADD FOREIGN KEY ("FRIEND_ID") REFERENCES "USERS" ("USER_ID");
