MERGE INTO RATINGS (RATING_ID, NAME) VALUES(1, 'G');
MERGE INTO RATINGS (RATING_ID, NAME) VALUES(2, 'PG');
MERGE INTO RATINGS (RATING_ID, NAME) VALUES(3, 'PG-13');
MERGE INTO RATINGS (RATING_ID, NAME) VALUES(4, 'R');
MERGE INTO RATINGS (RATING_ID, NAME) VALUES(5, 'NC-17');
MERGE INTO GENRES (GENRE_ID, NAME) VALUES(1, 'Комедия');
MERGE INTO GENRES (GENRE_ID, NAME) VALUES(2, 'Драма');
MERGE INTO GENRES (GENRE_ID, NAME) VALUES(3, 'Мультфильм');
MERGE INTO GENRES (GENRE_ID, NAME) VALUES(4, 'Триллер');
MERGE INTO GENRES (GENRE_ID, NAME) VALUES(5, 'Документальный');
MERGE INTO GENRES (GENRE_ID, NAME) VALUES(6, 'Боевик');
INSERT INTO users (email, login, name, birthday) VALUES ('email1@email.com', 'userlogin1', 'testname1', '2001-01-11');
INSERT INTO users (email, login, name, birthday) VALUES ('email2@email.com', 'userlogin2', 'testname2', '2001-01-12');
INSERT INTO users (email, login, name, birthday) VALUES ('email3@email.com', 'userlogin3', 'testname3', '2001-01-13');
INSERT INTO friends (user_id, friend_id) VALUES (3, 2);
INSERT INTO films (name, description, release_date, duration, mpa) VALUES ('Фильм 1', 'Самый интересный фильм 1', '1999-01-02', 111, 1);
INSERT INTO films (name, description, release_date, duration, mpa) VALUES ('Фильм 2', 'Самый интересный фильм 2', '1999-01-03', 222, 2);
INSERT INTO films (name, description, release_date, duration, mpa) VALUES ('Фильм 3', 'Самый интересный фильм 3', '1999-01-04', 333, 3);
INSERT INTO film_genres (film_id, genre_id) VALUES (1, 1);
INSERT INTO film_genres (film_id, genre_id) VALUES (1, 3);
INSERT INTO film_genres (film_id, genre_id) VALUES (2, 4);
INSERT INTO film_genres (film_id, genre_id) VALUES (2, 6);
INSERT INTO film_genres (film_id, genre_id) VALUES (3, 5);
INSERT INTO film_likes (film_id, user_id) VALUES (1, 1);
INSERT INTO film_likes (film_id, user_id) VALUES (1, 2);
INSERT INTO film_likes (film_id, user_id) VALUES (2, 1);
INSERT INTO film_likes (film_id, user_id) VALUES (2, 2);
INSERT INTO film_likes (film_id, user_id) VALUES (2, 3);
INSERT INTO film_likes (film_id, user_id) VALUES (3, 1);

